# Generated by Django 4.0 on 2021-12-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AlterField(
            model_name='todo',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Крайний срок'),
        ),
    ]
