# Generated by Django 4.0 on 2021-12-20 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_options_alter_todo_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('Срочно', 'Срочно'), ('Не срочно', 'Не срочно'), ('Очень срочно', 'Очень срочно')], max_length=250, verbose_name='Статус'),
        ),
    ]
